# FILEPATH: /Users/daiki/workspace/Tutorials/fastapi/docker-compose.yml

version: '3'
services:
  demo-app:
    build: .
    volumes:
      - .dockervenv:/srv/.venv
      - .:/src
    ports:
      - 8000:8000
    environment:
      - WATCHFILES_FORCE_POLING=true